name: Deploy cataemprego in dev stage

on:
  push:
    branches:
      - develop

env:
  SUPABASE_KEY: ${{secrets.SUBAPASE_KEY}}
  SUPABASE_URL: ${{secrets.SUPBASE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cataemprego" 
          heroku_email: "alinetgue@gmail.com"
          usedocker: true