name: Deploy cataemprego in dev stage

on:
  push:
    branches:
      - develop

env:
  SUPABASE_KEY: ${{secrets.SUBAPASE_KEY}}
  SUPABASE_URL: ${{secrets.SUPBASE_URL}}
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
  HEROKU_APP_NAME:  ${{secrets.HEROKU_APP_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login in Heroku
        run: heroku auth:login

      # - name: Login in Heroku Container Registry
      #   run: heroku container:login 

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          usedocker: true