name: Deploy cataemprego in dev stage

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      env:
        SUPABASE_KEY: ${{secrets.SUBAPASE_KEY}}
        SUPABASE_URL: ${{secrets.SUPBASE_URL}}
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        HEROKU_APP_NAME:  ${{secrets.HEROKU_APP_NAME}}

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku Container registry
        run: heroku container:login 

      - name: Build and push
        run: heroku container:push -a HEROKU_APP_NAME web 

      - name: Release
        run: heroku container:release -a HEROKU_APP_NAME web 
