name: Deploy cataemprego in dev stage

on:
  push:
    branches:
      - develop

env:
  SUPABASE_KEY: ${{secrets.SUBAPASE_KEY}}
  SUPABASE_URL: ${{secrets.SUPBASE_URL}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          justlogin: true